In [1]:
import math
import numpy as np
import pandas as pd

In [2]:
a = np.array(20)
a

array(20)

In [3]:
a = np.arange(20)
a= a.reshape(4,5,1)
a

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [4]:
print (a.shape)
print (a.ndim)
print (a.size)
print (a.dtype)

(4, 5, 1)
3
20
int32


In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [8]:
b

array([0, 1, 2, 3])

In [9]:
a

array([20, 30, 40, 50])

In [10]:
a - b

array([20, 29, 38, 47])

In [11]:
a * b

array([  0,  30,  80, 150])

In [12]:
b > 5

array([False, False, False, False])

In [13]:
np.sin(30)

-0.9880316240928618

In [14]:
pd.Series([1,2,3,'some name',np.nan,-1])

0            1
1            2
2            3
3    some name
4          NaN
5           -1
dtype: object

In [15]:
dates = pd.date_range("20220102", periods=6)
dates

DatetimeIndex(['2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05',
               '2022-01-06', '2022-01-07'],
              dtype='datetime64[ns]', freq='D')

In [16]:
np.random.rand(6,4)

array([[0.14034868, 0.51175142, 0.55458597, 0.05521577],
       [0.82201057, 0.11926802, 0.15068138, 0.98227424],
       [0.38778133, 0.98701694, 0.90565612, 0.57299148],
       [0.63268193, 0.4550483 , 0.64201314, 0.79000207],
       [0.69177283, 0.49383837, 0.15792204, 0.51141661],
       [0.51217235, 0.01049027, 0.00204267, 0.46078783]])

In [17]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])
df

A         B         C         D
2022-01-02  1.383853  0.496139 -0.003563  0.028637
2022-01-03 -0.676434 -0.737342  1.499218  0.570825
2022-01-04  1.052516  0.864283 -0.292109 -1.553630
2022-01-05 -0.267889 -0.892227  0.777776  0.022897
2022-01-06  0.407973  0.788359 -0.269925  0.901768
2022-01-07  0.802576 -1.035544  0.000161 -0.340765

In [18]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [19]:
df["A"]

2022-01-02    1.383853
2022-01-03   -0.676434
2022-01-04    1.052516
2022-01-05   -0.267889
2022-01-06    0.407973
2022-01-07    0.802576
Freq: D, Name: A, dtype: float64

In [20]:
print(df.head(2))
df.tail(2)

                   A         B         C         D
2022-01-02  1.383853  0.496139 -0.003563  0.028637
2022-01-03 -0.676434 -0.737342  1.499218  0.570825


A         B         C         D
2022-01-06  0.407973  0.788359 -0.269925  0.901768
2022-01-07  0.802576 -1.035544  0.000161 -0.340765

In [21]:
#mean is avarage! std is standadrd 
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.450432 -0.086055  0.285260 -0.061711
std    0.793145  0.892447  0.710289  0.854097
min   -0.676434 -1.035544 -0.292109 -1.553630
25%   -0.098924 -0.853506 -0.203334 -0.249849
50%    0.605274 -0.120602 -0.001701  0.025767
75%    0.990031  0.715304  0.583373  0.435278
max    1.383853  0.864283  1.499218  0.901768

In [22]:
df["A"].mean()


0.4504323798958934

In [23]:
df[1:3]

A         B         C         D
2022-01-03 -0.676434 -0.737342  1.499218  0.570825
2022-01-04  1.052516  0.864283 -0.292109 -1.553630

In [24]:
df.sort_values(by="B")

A         B         C         D
2022-01-07  0.802576 -1.035544  0.000161 -0.340765
2022-01-05 -0.267889 -0.892227  0.777776  0.022897
2022-01-03 -0.676434 -0.737342  1.499218  0.570825
2022-01-02  1.383853  0.496139 -0.003563  0.028637
2022-01-06  0.407973  0.788359 -0.269925  0.901768
2022-01-04  1.052516  0.864283 -0.292109 -1.553630

In [25]:
df[df["A"]>0]

A         B         C         D
2022-01-02  1.383853  0.496139 -0.003563  0.028637
2022-01-04  1.052516  0.864283 -0.292109 -1.553630
2022-01-06  0.407973  0.788359 -0.269925  0.901768
2022-01-07  0.802576 -1.035544  0.000161 -0.340765

In [26]:
# Read and write opereations

In [27]:
df.to_csv('df.csv')
df.to_excel('df.xlsx')