In [1]:
import math
import numpy as np
import pandas as pd

In [ ]:
a = np.array(20)
a

In [32]:
a = np.arange(20)
a= a.reshape(2,5,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [33]:
print (a.shape)
print (a.ndim)
print (a.size)
print (a.dtype)

(2, 5, 2)
3
20
int32


In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [37]:
b

array([0, 1, 2, 3])

In [38]:
a

array([20, 30, 40, 50])

In [39]:
a - b

array([20, 29, 38, 47])

In [40]:
a * b

array([  0,  30,  80, 150])

In [41]:
b > 5

array([False, False, False, False])

In [42]:
np.sin(30)

-0.9880316240928618

In [43]:
pd.Series([1,2,3,'some name',np.nan,-1])

0            1
1            2
2            3
3    some name
4          NaN
5           -1
dtype: object

In [44]:
dates = pd.date_range("20220102", periods=6)
dates

DatetimeIndex(['2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05',
               '2022-01-06', '2022-01-07'],
              dtype='datetime64[ns]', freq='D')

In [45]:
np.random.rand(6,4)

array([[0.58351516, 0.28214792, 0.11303777, 0.40924533],
       [0.72929215, 0.51475129, 0.54023274, 0.57775524],
       [0.75981604, 0.93531166, 0.09062449, 0.37094908],
       [0.61315154, 0.80703856, 0.58973192, 0.58118638],
       [0.19756132, 0.72833842, 0.30533391, 0.12636176],
       [0.22319911, 0.65360642, 0.46566414, 0.08921409]])

In [46]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['A','B','C','D'])
df

A         B         C         D
2022-01-02  0.392462  0.000096  1.588181 -1.422871
2022-01-03  1.731246 -1.040902  0.022882  0.408518
2022-01-04 -0.666852 -0.159230 -0.804007 -3.051109
2022-01-05  0.799640  1.239555 -0.878907 -2.122545
2022-01-06 -0.417375  1.890607  0.584800 -0.627513
2022-01-07 -0.745694 -0.582147 -0.269496  0.525289

In [47]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [48]:
df["A"]

2022-01-02    0.392462
2022-01-03    1.731246
2022-01-04   -0.666852
2022-01-05    0.799640
2022-01-06   -0.417375
2022-01-07   -0.745694
Freq: D, Name: A, dtype: float64

In [49]:
df.head(2)

A         B         C         D
2022-01-02  0.392462  0.000096  1.588181 -1.422871
2022-01-03  1.731246 -1.040902  0.022882  0.408518

In [50]:
#mean is avarage! std is standadrd 
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.182238  0.224663  0.040575 -1.048372
std    0.976356  1.118551  0.932361  1.419937
min   -0.745694 -1.040902 -0.878907 -3.051109
25%   -0.604482 -0.476418 -0.670380 -1.947627
50%   -0.012457 -0.079567 -0.123307 -1.025192
75%    0.697845  0.929690  0.444321  0.149510
max    1.731246  1.890607  1.588181  0.525289

In [51]:
df["A"].mean()


0.18223776112533105

In [52]:
df[1:3]

A         B         C         D
2022-01-03  1.731246 -1.040902  0.022882  0.408518
2022-01-04 -0.666852 -0.159230 -0.804007 -3.051109

In [53]:
df.sort_values(by="B")

A         B         C         D
2022-01-03  1.731246 -1.040902  0.022882  0.408518
2022-01-07 -0.745694 -0.582147 -0.269496  0.525289
2022-01-04 -0.666852 -0.159230 -0.804007 -3.051109
2022-01-02  0.392462  0.000096  1.588181 -1.422871
2022-01-05  0.799640  1.239555 -0.878907 -2.122545
2022-01-06 -0.417375  1.890607  0.584800 -0.627513

In [54]:
df[df["A"]>0]

A         B         C         D
2022-01-02  0.392462  0.000096  1.588181 -1.422871
2022-01-03  1.731246 -1.040902  0.022882  0.408518
2022-01-05  0.799640  1.239555 -0.878907 -2.122545

In [55]:
# Read and write opereations

In [56]:
df.to_csv('df.csv')
df.to_excel('df.xlsx')